# Generated by Django 4.2.6 on 2024-03-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0022_alter_restaurant_address_alter_restaurant_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='information',
            field=models.TextField(max_length=300, verbose_name='お店の説明'),
        ),
    ]
