# Generated by Django 4.2.6 on 2024-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0023_alter_restaurant_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=100, verbose_name='会員規約')),
            ],
        ),
    ]
