# Generated by Django 4.2.6 on 2024-03-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0024_reguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguration',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='規約名'),
        ),
        migrations.AlterField(
            model_name='reguration',
            name='text',
            field=models.TextField(default='', max_length=100, verbose_name='規約本文'),
        ),
    ]
