# Generated by Django 4.2.6 on 2024-03-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0028_alter_reguration_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genre_images', verbose_name='バナー画像'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ジャンル名'),
        ),
    ]
