# Generated by Django 4.2.6 on 2024-03-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0031_upgrade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upgrade',
            new_name='StripeCustomer',
        ),
    ]
