# Generated by Django 4.2.6 on 2024-03-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0032_rename_upgrade_stripecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True, verbose_name='年月')),
                ('total_sales', models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='合計売上')),
                ('paid_member_count', models.IntegerField(verbose_name='有料会員数')),
            ],
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
