# Generated by Django 4.2.6 on 2024-04-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0034_sales_delete_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月間売上')),
            ],
            options={
                'verbose_name': '月間売上',
                'verbose_name_plural': '月間売上管理',
            },
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
