# Generated by Django 4.2.6 on 2024-04-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0035_monthlysales_delete_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlySales',
        ),
    ]
