# Generated by Django 4.2.6 on 2024-04-04 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0036_delete_monthlysales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='年')),
                ('month', models.PositiveIntegerField(verbose_name='月')),
                ('is_paid_member', models.BooleanField(default=False, verbose_name='有料会員')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'サブスクリプションレコード',
                'verbose_name_plural': 'サブスクリプションレコード',
            },
        ),
    ]
