# Generated by Django 4.2.6 on 2024-04-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0037_subscription_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription_record',
            options={},
        ),
        migrations.AddField(
            model_name='subscription_record',
            name='price',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10, verbose_name='月額'),
        ),
    ]
