# Generated by Django 4.2.6 on 2024-04-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0038_alter_subscription_record_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_record',
            name='price',
        ),
    ]
