# Generated by Django 4.2.6 on 2024-04-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0039_remove_subscription_record_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription_record',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.RemoveField(
            model_name='subscription_record',
            name='is_paid_member',
        ),
    ]
