# Generated by Django 4.2.6 on 2024-04-09 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0040_alter_subscription_record_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name_alphabet',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$')], verbose_name='店舗名アルファベット表記'),
        ),
    ]
